// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6EDHeufqTaPPJmV687n6SHz4sBIjolOA',
    appId: '1:110965023013:web:19ef93879df10ceea33acc',
    messagingSenderId: '110965023013',
    projectId: 'authtutorial-1a245',
    authDomain: 'authtutorial-1a245.firebaseapp.com',
    storageBucket: 'authtutorial-1a245.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlFXVyfxxt2URZmItZFF8fKyusGt4xjk',
    appId: '1:110965023013:android:8c9bc4c7ad94857ba33acc',
    messagingSenderId: '110965023013',
    projectId: 'authtutorial-1a245',
    storageBucket: 'authtutorial-1a245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCY-sDJn5esKcex-J3U986SG8u_72jqoI',
    appId: '1:110965023013:ios:91d0026a8a72b5b6a33acc',
    messagingSenderId: '110965023013',
    projectId: 'authtutorial-1a245',
    storageBucket: 'authtutorial-1a245.appspot.com',
    iosBundleId: 'com.example.authenticationPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCY-sDJn5esKcex-J3U986SG8u_72jqoI',
    appId: '1:110965023013:ios:91d0026a8a72b5b6a33acc',
    messagingSenderId: '110965023013',
    projectId: 'authtutorial-1a245',
    storageBucket: 'authtutorial-1a245.appspot.com',
    iosBundleId: 'com.example.authenticationPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6EDHeufqTaPPJmV687n6SHz4sBIjolOA',
    appId: '1:110965023013:web:96b44b1eb3da6a8ca33acc',
    messagingSenderId: '110965023013',
    projectId: 'authtutorial-1a245',
    authDomain: 'authtutorial-1a245.firebaseapp.com',
    storageBucket: 'authtutorial-1a245.appspot.com',
  );
}
